name: MinecraftAuth
version: @VERSION@
main: me.minecraftauth.plugin.bukkit.MinecraftAuthBukkit
api-version: 1.15
authors: [ MinecraftAuth ]
description: Authenticate players in your Minecraft server to various services
website: https://minecraftauth.me
