name: Compile & push snapshots

on:
  push:
    branches:
      - devel

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build common library
        run: ./gradlew --no-daemon common:build
      - name: Build Bukkit plugin
        run: ./gradlew --no-daemon server:bukkit:build
      - name: Build Sponge plugin
        run: ./gradlew --no-daemon server:sponge:build
      - name: Build Forge 1.16.5 mod
        run: ./gradlew --no-daemon server:forge:1.16.5:build
      - name: Build Forge 1.18.2 mod
        run: ./gradlew --no-daemon server:forge:1.18.2:build
      - name: Build Forge 1.19.3 mod
        run: ./gradlew --no-daemon server:forge:1.19.3:build
      - name: Build BungeeCord plugin
        run: ./gradlew --no-daemon proxy:bungeecord:build
      - name: Build Velocity plugin
        run: ./gradlew --no-daemon proxy:velocity:build
      - name: Upload artifacts
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: snapshot
          rm: true
          files: |
            server/bukkit/build/libs/MinecraftAuth-Bukkit*.jar
            server/sponge/build/libs/MinecraftAuth-Sponge*.jar
            server/forge/*/build/libs/MinecraftAuth-Forge*.jar
            proxy/bungeecord/build/libs/MinecraftAuth-BungeeCord.jar
            proxy/velocity/build/libs/MinecraftAuth-Velocity.jar
