name: Compile & push snapshots

on:
  push:
    branches:
      - devel

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/**gradle**') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload artifacts
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: snapshot
          rm: true
          files: |
            bukkit/build/libs/MinecraftAuth-Bukkit*.jar
            sponge/build/libs/MinecraftAuth-Sponge*.jar
            forge/*/build/libs/MinecraftAuth-Forge*.jar
